apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: jchrisjordan/my-flask-app:v1
        ports:
        - containerPort: 8080
        command: ["flask", "run", "--host=0.0.0.0", "--port=8080", "--app", "my_flask_app:app"]
