apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: my-flask-app
spec:
  type: NodePort
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 8080  # The port on which this service is exposed
      targetPort: 8080  # The port on the pod that the traffic is forwarded to
      nodePort: 30001  # The port on the node to expose the service (range: 30000-32767)