name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  provision-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Provision Minikube Cluster
        run: |
          cd terraform-minikube
          terraform init
          terraform apply -auto-approve

  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Version
        id: version
        run: echo "::set-output name=version::$(date +'%Y.%m.%d.%H%M')"

      - name: Save Version
        run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" > version.txt

      - name: Commit Version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git commit -m "Bump version to ${{ steps.version.outputs.version }}"
          git push

  build:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          VERSION=$(cat version.txt)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:v2 -f app/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/my-flask-app

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run Tests
        run: curl http://<K8S_CLUSTER_IP>:<PORT> | grep "Hello, welcome to my simple HTTP REST application!"
